fix eitd: handle missing or failed demux gracefully
cst-build was broken

src/eitd/dmx.h:66:59: error: ‘class cDemux’ has no member named ‘getFD’


Origin commit data
------------------
Branch: master
Commit: https://github.com/neutrino-images/ni-neutrino/commit/f69a070c3d29bb16e0a557912f3c705a88a4dfd2
Author: vanhofen <vanhofen@gmx.de>
Date: 2026-02-17 (Tue, 17 Feb 2026)

Origin message was:
------------------
- fix a963bbc8264d5fbb68668e74a8eacb79ff2918bd; cst-build was broken

src/eitd/dmx.h:66:59: error: ‘class cDemux’ has no member named ‘getFD’


------------------
This commit was generated by Migit